export const actionTypes = {
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  FETCH_REQUEST: "FETCH_REQUEST",
  CATEGORIES: "CATEGORIES",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_ONE_FROM_CART: "ADD_ONE_FROM_CART",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  MINIMIZE: "MINIMIZE",
  CLEAR: "CLEAR",
  TOTAL: "TOTAL",
  TOTAL_MINUS_ONE: "TOTAL_MINUS_ONE",
};
