export const actionTypes = {
	FETCH_SUCCESS: 'FETCH_SUCCESS',
	FETCH_ERROR: 'FETCH_ERROR',
	FETCH_REQUEST: 'FETCH_REQUEST',
	CATEGORIES: 'CATEGORIES',
<<<<<<< HEAD
	CART_ITEMS: 'CART_ITEMS'
=======
	CART_ITEMS: 'CART_ITEMS',
	ADD_ITEM: 'REMOVE_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
>>>>>>> devel
}
